#!/bin/sh

muttrc=default
case $(hostname -f) in
  *.die-welt.net)
    muttrc=die-welt.net
    ;;
  *.redhat.com)
    muttrc=redhat.com
    ;;
esac

muttrc=${MUTTRC:-${muttrc}}

echo "source ~/.mutt/muttrc-${muttrc}"
